# Generated by Django 4.2.8 on 2023-12-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('productId', models.TextField()),
                ('userId', models.TextField()),
                ('profileName', models.TextField()),
                ('helpfulness', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score', models.IntegerField(default=0)),
                ('time', models.IntegerField()),
                ('summary', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
