# Generated by Django 4.2.8 on 2023-12-09 10:54

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('amazonreviewsapp', '0003_alter_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='time',
            field=django_unixdatetimefield.fields.UnixDateTimeField(),
        ),
    ]
